# Generated by Django 6.0.5 on 2026-05-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_category_options_alter_category_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Published", "Published")],
                default=0,
                max_length=20,
            ),
        ),
    ]
